local L = LibStub("AceLocale-3.0"):NewLocale("CC", "deDE")
if not L then return end

L["Add Spell"] = "Zauber hinzufügen"
L["All specified colors are vertex colors! (see wowwiki.com)"] = "Alle eingestellten Farben sind Vertex-Angaben! (siehe wowwiki.com)"
L["All unlockable modules are disabled!"] = "Alle freisetzbaren Module sind deaktiviert!"
L["Attach to cursor"] = "An Cursor anheften"
L["Auto arrange icons"] = "Symbole automatisch anordnen"
L["Background"] = "Hintergrund"
L["Bar"] = "Leiste"
L["Bar position saved!"] = "Leistenposition gespeichert!" -- ChatGPT
L["Border"] = "Rahmen"
L["Bottom"] = "Unten"
L["Bottom has to be a number!"] = "Unten muss eine Zahl sein!"
L["Cast color"] = "Farbe für Zauber"
L["Casttime"] = "Zauberzeit"
L["Color"] = "Farbe"
L["Colors"] = "Farben"
L["Display"] = "Anzeige"
L["Enabled"] = "Aktiviert"
L["Font"] = "Schrift"
L["Font Size"] = "Schriftgröße"
L["General"] = "Allgemein"
L["Hide default castbar"] = "Verstecke Standardzauberleiste"
L["Horizontal Offset"] = "Horizontaler Versatz" -- ChatGPT
L["Icon size"] = "Symbolgröße"
L["Latency color"] = "Farbe für Latenz"
L["Left"] = "Links"
L["Left has to be a number!"] = "Links muss eine Zahl sein!"
L["Midnight: GCD is not available in combat"] = "Midnight: GCD ist in Kampf nicht verfügbar"
L["Miscellaneous"] = "Sonstiges"
L["Position"] = "Position"
L["Primary"] = "Primär"
L["Radius"] = "Radius"
L["Remove Spell"] = "Zauber entfernen"
L["Restore defaults"] = "Standardwerte wiederherstellen"
L["Reverse channeling"] = "Umgekehrtes Channeling" -- ChatGPT
L["Right Click"] = "Rechtsklick" -- ChatGPT
L["Ring"] = "Ring"
L["Rotate"] = "Rotieren"
L["Secondary"] = "Sekundär"
L["Show spark only"] = "Zeige nur Funken"
L["Spark"] = "Funke"
L["Spell Text"] = "Zaubertext"
L["Spellcds"] = "Zauberabklingzeiten"
L["Spells"] = "Zauber"
L["Talent Specs"] = "Talentspezialisierungen"
L["Text"] = "Text"
L["Texture"] = "Textur"
L["to lock the cooldown bar and save its position"] = "um die Abklingzeitenleiste zu sperren und ihre Position zu speichern" -- ChatGPT
L["Thickness"] = "Dicke" -- ChatGPT
L["Unlock"] = "Freisetzen"
L["Vertical Offset"] = "Vertikaler Versatz" -- ChatGPT
L["Width"] = "Breite" -- ChatGPT
L["x-Offset"] = "X-Versatz" -- ChatGPT
L["y-Offset"] = "Y-Versatz" -- ChatGPT
