local L = LibStub("AceLocale-3.0"):NewLocale("CC", "koKR")
if not L then return end

L["Add Spell"] = "주문 추가"
L["All specified colors are vertex colors! (see wowwiki.com)"] = "모든 지정된 색상은 정점 색상입니다! (wowwiki.com 참조)" -- ChatGPT
L["All unlockable modules are disabled!"] = "모든 잠금 해제 가능한 모듈이 비활성화되었습니다!" -- ChatGPT
L["Attach to cursor"] = "커서에 붙이기"
L["Auto arrange icons"] = "자동 아이콘 정렬"
L["Background"] = "배경"
L["Bar"] = "막대"
L["Bar position saved!"] = "막대 위치가 저장되었습니다!" -- ChatGPT
L["Border"] = "경계"
L["Bottom"] = "바닥"
L["Bottom has to be a number!"] = "하단은 숫자여야 합니다!" -- ChatGPT
L["Cast color"] = "시전 색상"
L["Casttime"] = "시전시간"
L["Color"] = "색상"
L["Colors"] = "색상"
L["Display"] = "표시"
L["Enabled"] = "사용"
L["Font"] = "폰트"
L["Font Size"] = "폰트 크기"
L["General"] = "일반" -- ChatGPT
L["Hide default castbar"] = "기본 시전바 숨기기"
L["Horizontal Offset"] = "수평 오프셋" -- ChatGPT
L["Icon size"] = "아이콘 크기" -- ChatGPT
L["Latency color"] = "지연 색상"
L["Left"] = "왼쪽"
L["Left has to be a number!"] = "왼쪽은 숫자여야 합니다!" -- ChatGPT
L["Midnight: GCD is not available in combat"] = "Midnight: 전투 중에는 GCD를 사용할 수 없습니다"
L["Miscellaneous"] = "기타"
L["Position"] = "위치"
L["Primary"] = "기본" -- ChatGPT
L["Radius"] = "반지름"
L["Remove Spell"] = "주문 제거"
L["Restore defaults"] = "기본값 복구"
L["Reverse channeling"] = "역 채널링" -- ChatGPT
L["Right Click"] = "우클릭" -- ChatGPT
L["Ring"] = "고리" -- ChatGPT
L["Rotate"] = "회전"
L["Secondary"] = "보조" -- ChatGPT
L["Show spark only"] = "불꽃만 표시" -- ChatGPT
L["Spark"] = "불꽃" -- ChatGPT
L["Spell Text"] = "주문명"
L["Spellcds"] = "주문 재사용 대기시간" -- ChatGPT
L["Spells"] = "주문"
L["Talent Specs"] = "특성 스펙"
L["Text"] = "텍스트"
L["Texture"] = "텍스쳐"
L["to lock the cooldown bar and save its position"] = "재사용 대기시간 막대를 잠그고 위치를 저장하려면" -- ChatGPT
L["Thickness"] = "두께" -- ChatGPT
L["Unlock"] = "잠금 해제"
L["Vertical Offset"] = "수직 오프셋" -- ChatGPT
L["Visibility"] = "표시"
L["GCD / Casting only"] = "GCD / 시전만"
L["In combat"] = "전투 중"
L["In raid"] = "공격대"
L["In party/raid"] = "파티/공격대"
L["Always"] = "항상"
L["Width"] = "너비" -- ChatGPT
L["x-Offset"] = "x축"
L["y-Offset"] = "y축"
L["Filter"] = "필터"
L["Role filter"] = "역할 필터"
L["When enabled, the addon is hidden when your current spec's role is disabled below."] = "활성화하면 현재 특성의 역할이 아래에서 비활성화된 경우 애드온이 숨겨집니다."
L["Enable role filter"] = "역할 필터 사용"
