local L = LibStub("AceLocale-3.0"):NewLocale("CC", "zhCN")
if not L then return end

L["Add Spell"] = "增加法术"
L["All specified colors are vertex colors! (see wowwiki.com)"] = "请注意所有特定的颜色都是顶点色"
L["All unlockable modules are disabled!"] = "所有未解锁的模块已禁用！"
L["Attach to cursor"] = "吸附到光标"
L["Auto arrange icons"] = "自动排列图标"
L["Background"] = "背景"
L["Bar"] = "条"
L["Bar position saved!"] = "能量条位置已保存！" -- ChatGPT
L["Border"] = "边框"
L["Bottom"] = "底部"
L["Bottom has to be a number!"] = "底部应当是一个数字!"
L["Cast color"] = "施法显示颜色"
L["Casttime"] = "施法时间"
L["Color"] = "颜色"
L["Colors"] = "颜色"
L["Display"] = "显示"
L["Enabled"] = "启用"
L["Font"] = "字体"
L["Font Size"] = "字体大小"
L["General"] = "综合"
L["Hide default castbar"] = "隐藏默认施法条"
L["Horizontal Offset"] = "水平偏移" -- ChatGPT
L["Icon size"] = "图标大小"
L["Latency color"] = "延迟颜色"
L["Left"] = "左"
L["Left has to be a number!"] = "左边应当是一个数字!"
L["Midnight: GCD is not available in combat"] = "Midnight：战斗中无法显示GCD"
L["Miscellaneous"] = "杂项"
L["Position"] = "位置"
L["Primary"] = "首要"
L["Radius"] = "半径"
L["Remove Spell"] = "移除法术"
L["Restore defaults"] = "恢复默认设置"
L["Reverse channeling"] = "反向引导" -- ChatGPT
L["Right Click"] = "右键点击" -- ChatGPT
L["Ring"] = "环样式"
L["Rotate"] = "旋转"
L["Secondary"] = "次要"
L["Show spark only"] = "仅显示火花"
L["Spark"] = "闪光样式"
L["Spell Text"] = "法术文本"
L["Spellcds"] = "法术CD"
L["Spells"] = "法术"
L["Talent Specs"] = "双天赋"
L["Text"] = "文字"
L["Texture"] = "材质"
L["to lock the cooldown bar and save its position"] = "锁定冷却条并保存其位置" -- ChatGPT
L["Thickness"] = "粗细" -- ChatGPT
L["Unlock"] = "解锁"
L["Vertical Offset"] = "垂直偏移" -- ChatGPT
L["Width"] = "宽度" -- ChatGPT
L["x-Offset"] = "x-坐标"
L["y-Offset"] = "y-坐标"
